# Core module -- security, versioning, licensing, persistence
from core.licensing import (
    TIERS,
    LicenseCertificate,
    LicenseKeyPair,
    LicenseManager,
    get_hardware_fingerprint,
    get_hardware_hash,
)
from core.persistence import AlgorithmRegistry, DataStore, SessionManager
from core.security import (
    AuditLog,
    BinarySignature,
    Ed25519KeyPair,
    KeyPair,
    KeyStore,
    ProofCertificate,
    RateLimiter,
    SecureChannel,
    SecureSandbox,
    compute_hmac,
    ed25519_public_from_private,
    ed25519_sign,
    ed25519_verify,
    hash_data,
    hash_file,
    sign_binary,
    verify_hmac,
)
from core.versioning import CURRENT_VERSION, VersionManager

__all__ = [
    "KeyStore",
    "KeyPair",
    "Ed25519KeyPair",
    "ed25519_sign",
    "ed25519_verify",
    "ed25519_public_from_private",
    "ProofCertificate",
    "BinarySignature",
    "sign_binary",
    "SecureChannel",
    "AuditLog",
    "SecureSandbox",
    "RateLimiter",
    "hash_data",
    "hash_file",
    "compute_hmac",
    "verify_hmac",
    "VersionManager",
    "CURRENT_VERSION",
    "LicenseManager",
    "LicenseCertificate",
    "LicenseKeyPair",
    "get_hardware_fingerprint",
    "get_hardware_hash",
    "TIERS",
    "DataStore",
    "SessionManager",
    "AlgorithmRegistry",
]
